version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: wine-backend
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
      - ./model:/app/model
    environment:
      - FLASK_ENV=production
    networks:
      - monitor-net

  frontend:
    build:
      context: ./frontend
    container_name: wine-frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - monitor-net

  mlflow:
    image: ghcr.io/mlflow/mlflow
    container_name: mlflow
    ports:
      - "5001:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    command: mlflow server --host 0.0.0.0 --backend-store-uri /mlflow/mlruns
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge
